- package-lock.json
- package.json
- src/App.tsx
- src/pages/alarm/alarm.tsx
- src/pages/auth/login.tsx
- src/pages/auth/signin.tsx
- src/pages/board/board.tsx
- src/pages/board/create.tsx
- src/pages/board/free.tsx
- src/pages/board/mbti.tsx
- src/pages/board/update.tsx
- src/pages/chatting/chatting.tsx
- src/pages/debate/create.tsx
- src/pages/debate/debate.tsx
- src/pages/debate/update.tsx
- src/pages/favorites/favorites.tsx
- src/pages/main/main.tsx
- src/pages/matching/matching.tsx
- src/pages/mbtitype/mbtitype.tsx
- src/pages/user/user.tsx
- close #3 
중첩 라우팅일 경우는 outlet 사용해야 뜹니다!
등등등 ...
> [Docs] 페이지 분리 라우트 작성

- package-lock.json
- package.json
- src/App.tsx
- src/components/layout/layout.tsx
- src/pages/alarm/alarm.tsx
- src/pages/auth/login.tsx
- src/pages/auth/signin.tsx
- src/pages/board/board.tsx
- src/pages/board/create.tsx
- src/pages/board/free.tsx
- src/pages/board/mbti.tsx
- src/pages/board/update.tsx
- src/pages/chatting/chatting.tsx
- src/pages/debate/create.tsx
- src/pages/debate/debate.tsx
- src/pages/debate/update.tsx
- src/pages/favorites/favorites.tsx
- src/pages/main/main.tsx
- src/pages/matching/matching.tsx
- src/pages/mbtitype/mbtitype.tsx
- src/pages/user/user.tsx
- src/styles/color.ts
- close #1 
color 사용하실 때 이런 식으로 사용하시면 돼요!
> [Design] layout 컴포넌트, 공통 color 설정

- package-lock.json
- package.json
- src/components/header/Header.tsx
- src/components/layout/layout.tsx
- src/states/navbar.ts
- close #9 
header 부분은 기능 구현되면서 디자인 뿐만 아니라 많이 수정될 예정입니다!
https://github.com/Help-M-Ssaem/front-end/assets/97819580/9db1c5e6-340e-4abf-8752-84472d866fbf
> [Fix] header 컴포넌트 navbar 라우팅 오류 수정

- package-lock.json
- package.json
- public/index.html
- src/components/header/Header.tsx
- src/styles/GlobalStyle.tsx
- src/styles/font.ts
- close #12 
폰트를 설정하지 않고, 진행하려다 보니 font size나 font weight 등
피그마와 차이가 많이 나서 전역으로 설정했습니다~~ 확인해주세용
작업 상세 내용
> [Design] pretendard 전역 글꼴 설정

- package-lock.json
- package.json
- src/App.tsx
- src/assets/HeaderIcons.tsx
- src/components/button/Button.tsx
- src/components/container/Container.tsx
- src/components/header/Header.tsx
- src/components/layout/Layout.tsx
- src/components/scroll/ScrollToTop.tsx
- src/pages/board/create.tsx
- src/pages/board/mbti.tsx
- src/styles/color.ts
- src/styles/font.ts
- #8 
https://www.npmjs.com/package/@toast-ui/react-editor
toast-ui/react-editor 라이브러리를 썼어요!
아직 서버에 보내는 처리는 안 했어요!
추가로, header logo 크기나 높이가 큰 것 같아서 줄였어요
게시판 생성 페이지 디자인이 좀 많이 바뀐 것 같은데 수정할 부분 있으면 리뷰 남겨주세요!
https://github.com/Help-M-Ssaem/front-end/assets/97819580/3a512cf8-6a81-4aa4-bdde-534ee95e2ef3
> [Feat] 게시판 생성 페이지 완료 editor

- src/App.tsx
- src/assets/CommonIcons.tsx
- src/components/badge/Badge.tsx
- src/components/header/Header.tsx
- src/components/matching/Matching.tsx
- src/interfaces/matching.ts
- src/pages/board/mbti.tsx
- src/pages/matching/create.tsx
- src/pages/matching/match.tsx
- src/pages/matching/matching.tsx
- src/pages/matching/update.tsx
- close #22 
아직 생성, 수정, 디테일 페이지 디자인이 나오지 않아, 조회 페이지만 구현했어용!
> [Design] Matching 페이지 디자인

- .gitignore
- package-lock.json
- package.json
- src/App.tsx
- src/apis/axios.ts
- src/components/auth/Login.tsx
- src/components/auth/NotLogin.tsx
- src/components/badge/Badge.tsx
- src/components/container/Container.tsx
- src/components/main/Hot.tsx
- src/components/profile/Profile.tsx
- src/components/text/Text.tsx
- src/constants/boardKey.ts
- src/hooks/main/useHotBoard.tsx
- src/interfaces/board.ts
- src/interfaces/user.ts
- src/pages/board/mbti.tsx
- src/pages/main/main.tsx
- src/pages/user/user.tsx
- #28
아직 더미데이터가 업로드되지 않아 any 타입으로 일시적으로 만들었어요. 데이터 추가되면 수정할 예정입니다.
서버 연결하기 위해선 .env 파일을 루트에 추가해야되는데 노션을 참고해주시고 형식은 코드를 참고해주세요!!
https://github.com/Help-M-Ssaem/front-end/assets/97819580/d79c5158-8d70-49f9-9357-909bc37e9d65
> [Design] Main 페이지 디자인, 서버 연결 설정

- src/App.tsx
- src/apis/axios.ts
- src/components/auth/NotLogin.tsx
- src/components/board/Board.tsx
- src/components/header/Header.tsx
- src/constants/boardKey.ts
- src/hooks/board/useCreateBoard.tsx
- src/interfaces/board.ts
- src/pages/board/create.tsx
- src/pages/board/detail.tsx
- src/pages/board/mbti.tsx
- close #33 
서버 연결에 어려움 느끼시는 분들 연락주세요!!
react-query 처음 공부할 때 저도 엄청 어려웠어서 도움드릴 수 있습니다!ㅠㅠㅠ
빛나는 200!!!!
> [Feat] 서버 연결 테스트용 마스터 계정 추가

- src/hooks/board/useCreateBoard.tsx
- src/hooks/board/useDeleteBoard.tsx
- src/hooks/board/useUpdateBoard.tsx
- src/interfaces/board.ts
- src/pages/board/create.tsx
- src/pages/board/detail.tsx
- src/pages/board/update.tsx
- #38 
아직 만들어진 것을 조회하진 못하기 때문에 update, delete 직접 확인을 하지 못합니다!!
그래도 200 뜬 거 확인해서 올려요~~~
게시판 생성
게시판 수정
게시판 삭제
게시판 생성된 id로 넣어야 되는데 아직 조회가 구현 안돼서 게시글 존재 오류가 뜹니다! (조회 연결되면 해결!)
> [Feat] MBTI별 게시판 페이지 create, update, delete api 연동

- src/App.tsx
- src/components/header/Header.tsx
- src/components/main/HotBoard.tsx
- src/hooks/board/useCreateBoard.tsx
- src/hooks/board/useDeleteBoard.tsx
- src/hooks/board/useUpdateBoard.tsx
- src/hooks/main/useHotBoard.tsx
- src/hooks/main/useHotBoardMore.tsx
- src/hooks/main/useHotDebate.tsx
- src/hooks/main/useHotDebateMore.tsx
- src/interfaces/board.ts
- src/interfaces/debate.ts
- src/pages/board/create.tsx
- src/pages/board/detail.tsx
- src/pages/board/update.tsx
- src/pages/main/hotBoard.tsx
- src/pages/main/hotDebate.tsx
- src/pages/main/main.tsx
- #35
아직 페이지네이션을 구현하지 않아서 page를 1과 size를 6으로 설정해놨습니다.
페이지네이션 공통 컴포넌트 구현하면 수정하겠습니다!
프로필과 썸네일 사진이 더미데이터에 없어서 이상하게 보입니다! 참고해주세요
> [Feat] 메인 페이지 HOT 게시글, 토론 더보기 api 연동

- src/App.tsx
- src/components/mypage/MyPage.tsx
- src/interfaces/board.ts
- src/pages/mypage/mypage.tsx
- #44
- 아직 서버가 완성 안되어서 더미데이터로 들어감
- 내 게시물 등 컴포넌트 불러오는 부분은 깨져보임 -> 컴포넌트 불러오고 삭제할거라서 이런느낌이다 보시면 됩니다.
- 피드백 수정
> [Design] 마이페이지

- src/App.tsx
- src/components/mypage/MyPage.tsx
- src/interfaces/board.ts
- src/pages/mypage/mypage.tsx
ex) [Design] #45  , [Fix] #46 
> [Fix] interface conflict 수정

- src/App.tsx
- src/components/header/Header.tsx
- src/pages/mypage/mypage.tsx
- src/pages/search/search.tsx
ex) [Design] #51 
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 
https://github.com/Help-M-Ssaem/front-end/assets/109562161/8ad224a4-5945-47d9-bf37-79e62965b7f5
> [Design] 검색페이지

- src/components/auth/Callback.tsx
- src/hooks/user/signup.tsx
- src/hooks/user/userlogin.tsx
- src/hooks/worry/useCreateWorry.tsx
- src/hooks/worry/useDeleteWorry.tsx
- src/hooks/worry/useUpdatedWorry.tsx
- src/interfaces/signup.ts
- src/interfaces/userinfo.ts
- src/interfaces/worry.ts
- src/pages/auth/UserInfo.tsx
- src/pages/auth/login.tsx
- src/pages/auth/signin.tsx
- src/pages/matching/create.tsx
- src/pages/matching/detail.tsx
- src/pages/matching/matching.tsx
- src/pages/matching/update.tsx
- #32 
1. 소셜 로그인 이슈 브랜치는 아닌데, 기능 적용되어있어서 설명 같이 올려요! 
카카오톡만 서버 연결이 되어있기 때문에, 카카오톡만 해보셔야해요!
*회원가입 안되어있으면 이용약관 페이지 -> 유저 정보 페이지로 이동
*회원가입 되어있으면 메인 페이지로 이동
2. 고민글도 이쪽 브랜치가 아닌데.. pull 하시거나, 이어서 하실 때 참고해주세요!
*고민글은 수정,삭제, 작성 서버만 연결했습니다
3. 유저정보페이지 컴포넌트 분리
열심히 분리를 시도했으나, 실패했습니당... 워낙 useState 가 많이 사용되었고, 코드가 좀 복잡해서... 분리했더니 결국 원래 코드랑 별차이 없이 길더라구요...ㅜㅜ 그래서 일단은 그냥 올립니다..ㅠㅠ
4. 그리고 저 develop pull 받았는데 다른 페이지 이러는 거 맞아여....??? 영상 확인 부탁드려요 ㅜㅜ
https://github.com/Help-M-Ssaem/front-end/assets/101424642/77dff72f-cfd9-44c9-a218-1b1b81586d80
> [Feat] 회원가입 연결

- src/components/matching/Matching.tsx
- src/components/matching/mapingMatching/WorryList.tsx
- src/hooks/main/useMainTeacher.tsx
- src/interfaces/worry.ts
- src/pages/matching/detail.tsx
- #78 
아직 고민글 서버 이미지 업로드 업데이트가 안되서 이미지 업로드는 아직 안되용..
> [Design] 고민글 인터페이스 및 디자인 수정

- src/components/matching/mapingMatching/WorryList.tsx
- src/hooks/worry/UseFetchBoardList.tsx
- src/hooks/worry/useWorryPostListMember.tsx
- src/hooks/worry/useWorrySolveListMember.tsx
- src/interfaces/worry.ts
- src/pages/debate/create.tsx
- src/pages/debate/detail.tsx
- src/pages/mypage/mypage.tsx
- #84
해결한 게시글을 게시한 글이 점령했어요 한번 쓱봐주세요 ㅠㅠ
> [Feat] 고민글 페이지, 특정 멤버조회

- src/components/debate/pageMapingDebate/PageDebate.tsx
- src/components/debate/vote/VoteItem.tsx
- src/components/main/HotDebate.tsx
- src/hooks/debate/useDebatePaging.tsx
- src/pages/debate/detail.tsx
- src/pages/debate/postlist.tsx
- src/pages/main/hotDebate.tsx
- src/pages/main/main.tsx
#68 
현재 게시글 생성이 없는 관계로 게시글의 수를 늘려서 확인해야합니다.
key와 query에 대한 이해가 좀 부족한 것 같습니다. 
페이지네이션 기능은 작동하지만 해당 부분을 제거하고 사용하고 있습니다.
상세조회에서 참여중 디자인 및 댓글작성 연동
> [Feat] Hot토론글, 토론글 페이지네이션

- src/components/debate/vote/VoteItem.tsx
- src/components/debate/vote/VoteItemList.tsx
- src/components/matching/Matching.tsx
- src/components/matching/mapingMatching/MbtiList.tsx
- src/components/matching/mapingMatching/WorryList.tsx
- src/hooks/debate/comment/useDebateCommentCreate.tsx
- src/hooks/debate/comment/useDebateCommentDelete.tsx
- src/hooks/debate/useCreateDebate.tsx
- src/hooks/debate/useDeleteDebate.tsx
- src/hooks/debate/useDetailDebate.tsx
- src/hooks/worry/UseFetchBoardList.tsx
- src/hooks/worry/useCreateWorry.tsx
- src/hooks/worry/useDetailPost.tsx
- src/hooks/worry/useWorryPostListMember.tsx
- src/hooks/worry/useWorrySolveListMember.tsx
- src/interfaces/debate.ts
- src/interfaces/worry.ts
> [Fix] conflict 중간 점검

- src/pages/mypage/mypage.tsx
#89 
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 
https://github.com/Help-M-Ssaem/front-end/assets/109562161/7844d3f7-efa5-41f9-9bc1-723f31e2ef97
> [Fix] conflict 추가 수정

- src/components/board/Board.tsx
- src/components/main/HotBoard.tsx
- src/components/main/HotDebate.tsx
- #71 
HOT 게시글 페이지네이션은 글이 없어서 테스트 못해봤습니다.
> [Fix] 메인페이지 관련 오류 수정

- src/components/matching/mapingMatching/WorryList.tsx
- src/components/text/Text.tsx
- src/hooks/board/useBoardList.tsx
- src/interfaces/board.ts
- src/pages/board/board.tsx
- src/pages/board/create.tsx
- src/pages/board/detail.tsx
- src/pages/board/mbti.tsx
- src/pages/main/hotBoard.tsx
- src/pages/main/hotDebate.tsx
- src/pages/main/main.tsx
- src/pages/matching/matching.tsx
- #70 
https://github.com/Help-M-Ssaem/front-end/assets/97819580/0c4d9e86-9dcc-4897-a242-bac8aca9df2d
> [Fix] MBTI별 게시판 관련 오류

- src/components/auth/Login.tsx
- src/components/header/Header.tsx
- src/constants/userKey.ts
- src/hooks/board/useBoardListMember.tsx
- src/hooks/user/useMemberInfo.tsx
- src/hooks/user/useProfile.tsx
- src/interfaces/user.ts
- src/pages/main/main.tsx
- src/pages/mypage/mypage.tsx
- src/pages/mypage/update.tsx
> [Feat] 현재 로그인한 회원 정보 조회

- src/hooks/search/search.tsx
- src/pages/search/result.tsx
> Fix: search hooks 관련 이슈 수정 (#121)

- src/components/board/comment/CommentCreate.tsx
> [Fix] 댓글 관련 오류

- src/apis/axios.ts
- src/components/text/Text.tsx
- src/interfaces/board.ts
- src/pages/board/create.tsx
- src/pages/board/detail.tsx
- src/pages/board/mbti.tsx
- src/pages/board/update.tsx
> [Fix] 게시판 관련 오류

- src/apis/axios.ts
- src/components/auth/Login.tsx
- src/components/board/Board.tsx
- src/components/board/comment/Comment.tsx
- src/components/debate/debate.tsx
- src/components/debate/myDebate.tsx
- src/components/header/Header.tsx
- src/components/main/HotBoard.tsx
- src/components/main/HotDebate.tsx
- src/components/profile/Profile.tsx
- src/pages/board/detail.tsx
- src/pages/chatting/chatting.tsx
- src/pages/debate/detail.tsx
> [Fix] 프로필 관련 오류

- src/components/badge/Badge.tsx
- src/components/chatting/CurrentChatting.tsx
- src/components/main/HotWorry.tsx
- src/components/matching/Matching.tsx
- src/components/matching/Mssaem.tsx
- src/components/modal/EvaluationModal.tsx
- src/components/profile/MatchingProfile.tsx
- src/components/profile/Profile.tsx
- src/styles/color.ts
- #147
mbti default 프로필 고양이 색상으로 추가했어요!
> [Design]  MBTI별 Badge 색상

- src/pages/board/create.tsx
- src/pages/board/update.tsx
> [Fix] MBTI별 게시판 최종 사진 업로드 추가

- src/components/debate/pageMapingDebate/PageDebate.tsx
- src/components/debate/vote/VoteItem.tsx
- src/components/main/HotWorry.tsx
- src/components/matching/Matching.tsx
- src/hooks/alarm/usePageAlarm.tsx
- src/hooks/debate/useDebatePaging.tsx
- src/hooks/debate/useVoteItem.tsx
- src/pages/alarm/alarm.tsx
- src/pages/main/main.tsx
- src/pages/matching/detail.tsx
- src/pages/matching/matching.tsx
> [Fix] 토론 페이지네이션 훅 수정, 투표시 바로 반영

- src/components/chatting/CurrentChatting.tsx
> [Fix]  해결완료 수정

- src/components/mypage/MyPage.tsx
- src/pages/usePage/UserPage.tsx
- src/pages/usePage/mypage.tsx
- src/pages/usePage/update.tsx
> [Fix] 유저 수정페이지 오류 수정

- src/components/debate/debate.tsx
- src/components/debate/vote/VoteItem.tsx
- src/components/matching/mapingMatching/WorryList.tsx
- src/components/modal/ReportModal.tsx
- src/components/modal/ShareModal.tsx
- src/hooks/report/useReportPost.tsx
- src/interfaces/worry.ts
- src/pages/matching/detail.tsx
> [Fix] 고민/토론 일부 수정 

- src/App.tsx
- src/components/auth/Login.tsx
- src/hooks/user/useMemberInfo.tsx
- src/pages/usePage/update.tsx
- **  배포되면 테스트 필요 **
- 아직 테스트 안해봄... 
> [Fix] 유저 수정 페이지, 로그아웃 수정 

- src/components/auth/Login.tsx
- src/pages/usePage/update.tsx
> [Fix] 로그아웃 수정

- src/components/matching/mapingMatching/WorryList.tsx
- src/pages/main/main.tsx
- src/pages/search/search.tsx
> [Fix] 고민글 리로딩 제거

- src/components/badge/Badge.tsx
- src/pages/userPage/mypage.tsx
- src/pages/userPage/update.tsx
> [Fix] 유저수정페이지 

- src/components/mypage/ActivityList.tsx
- src/pages/userPage/UserPage.tsx
- src/pages/userPage/mypage.tsx
- src/pages/userPage/update.tsx
> [Fix] 유저페이지비율수정

- src/components/modal/EvaluationModal.tsx
> [Fix]  평가하기 여러개 

- src/components/auth/Callback.tsx
- src/components/modal/EvaluationModal.tsx
- src/pages/auth/UserInfo.tsx
- src/pages/auth/login.tsx
- src/pages/main/main.tsx
- src/pages/userPage/mypage.tsx
로그아웃, 회원가입의 경우는 배포되면 테스트할 수 있어서,,, 로컬에서는 할 수 있는게 없어여 ㅜㅜ 
일단 수정한거 배포되면 테스트 해볼게여..ㅜ 
아마 다시 수정해야할듯하지만
> [Fix] 로그아웃 에러 , 평가하기 에러 

- src/components/auth/Login.tsx
- src/pages/main/main.tsx
- src/pages/userPage/update.tsx
> [Fix] 로그아웃 수정  

- src/pages/auth/login.tsx
> [Fix] 로그아웃 수정 

- src/pages/main/main.tsx
> [Fix] 새로고침 수정

- src/pages/userPage/mypage.tsx
> [Fix ] 유저 페이지 이미지 비율 조정

- src/apis/axios.ts
- src/components/Pagination/SelectBox.tsx
- src/components/debate/pageMapingDebate/PageDebate.tsx
- src/components/matching/mapingMatching/WorryList.tsx
- src/interfaces/worry.ts
- src/pages/board/mbti.tsx
- src/pages/main/hotBoard.tsx
- src/pages/search/moreBoardResult.tsx
- src/pages/search/moreDebateResult.tsx
- src/pages/search/moreMatchingResult.tsx
- src/pages/search/result.tsx
- src/pages/userPage/mypage.tsx
#206 #222
#206 
https://github.com/Help-M-Ssaem/front-end/assets/109562161/f306155a-16eb-44b9-ac9c-9bd9a75834c3
#222
https://github.com/Help-M-Ssaem/front-end/assets/109562161/5c4adff5-e383-45fb-8ab4-7f3b4a3fc4a1
> Feat: 게시판 검색 API 연결

- src/components/Pagination/SelectBox.tsx
- src/components/debate/pageMapingDebate/PageDebate.tsx
- src/components/header/Header.tsx
- src/components/matching/mapingMatching/WorryList.tsx
- src/interfaces/worry.ts
- src/pages/board/mbti.tsx
- src/pages/main/hotBoard.tsx
- src/pages/search/moreBoardResult.tsx
- src/pages/search/moreDebateResult.tsx
- src/pages/search/moreMatchingResult.tsx
- src/pages/search/result.tsx
- src/pages/userPage/mypage.tsx
Reverts Help-M-Ssaem/front-end#223
> Revert "Feat: 게시판 검색 API 연결"

- src/components/header/Header.tsx
- src/components/modal/ShareModal.tsx
- src/hooks/debate/useDebatePaging.tsx
- src/hooks/debate/useDetailDebate.tsx
- src/pages/debate/detail.tsx
> [Fix] 토론글 로딩 추가

- src/components/auth/Login.tsx
- src/pages/auth/login.tsx
> [Fix] 로그아웃 url 수정, 네이버 버튼 제거 

- src/apis/axios.ts
- src/components/Pagination/SelectBox.tsx
- src/components/debate/pageMapingDebate/PageDebate.tsx
- src/components/header/Header.tsx
- src/components/matching/mapingMatching/WorryList.tsx
- src/components/modal/ShareModal.tsx
- src/components/search/SearchBar.tsx
- src/hooks/debate/useDebatePaging.tsx
- src/hooks/debate/useDetailDebate.tsx
- src/hooks/keywords/usePostSearchWord.tsx
- src/interfaces/worry.ts
- src/pages/board/mbti.tsx
- src/pages/debate/detail.tsx
- src/pages/main/hotBoard.tsx
- src/pages/search/moreBoardResult.tsx
- src/pages/search/moreDebateResult.tsx
- src/pages/search/moreMatchingResult.tsx
- src/pages/search/result.tsx
- src/pages/userPage/UserPage.tsx
- src/pages/userPage/mypage.tsx
> [Fix] 유저관련페이지 수정, 검색 시 공백제한
